### PR TITLE
Added helloworld.cpp file that outputs Hello World to console.

### PR DESCRIPTION
**Pull request by YakavenkaM**
First Assignment completed by Mikhail Yakavenka.
Added helloworld.cpp file.

Compiled and ran.Prints out Hello World.
@rivlev @andreas-weise

### CODE REVIEW

**Comment by andreas-weise** [comment]
9.5/10 

Please submit only the relevant code, not all auxiliary files.

**Comment by andreas-weise** [comment]
9.5/10 

Please submit only the relevant code, not all auxiliary files.

**Comment by YakavenkaM** [comment]
Should I remove them on github or should I re-do whole assignment via vi?
I would like to have 10/10 for it.

Thank you.


Mikhail.

**Comment by YakavenkaM** [comment]
I see that I am not allowed to delete the .idea files from github directly.
I have a vi edited .cpp file ready to push.
Please let me know how you prefer I do that.

Thank you.

**Comment by YakavenkaM** [comment]
Okay, sorry for so many questions and emails.
I created new project via vi, pulled the code, removed files and pushed out
updated hw branch.
Please let me know if I need to do another "new pull request"

Thanks again, will wait for your response.

Have a great weekend!
Mikhail.

**Comment by andreas-weise** [comment]
I have talked to Professor Levitan. If you submit a "clean" pull request before the deadline, you can still earn full points. So yes, you do need to create a new pull request and it should only contain the single cpp file and should mention her and myself.

**Comment by YakavenkaM** [comment]
Thank you so much for your help.
Will do!

**Pull request closed without merging**
